language: c
sudo: required
dist: trusty
cache: ccache
services:
  - docker
env:
  - TR_ARCH=aarch64     CLANG=1
matrix:
  allow_failures:
    - env: TR_ARCH=docker-test
    - env: TR_ARCH=fedora-rawhide
script:
  - sudo make CCACHE=1 -C scripts/travis $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/travis after_success
group: deprecated-2017Q2
